version: '3.8'

services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../backend:/app
      - /app/node_modules

  admin-web:
    build:
      context: ../apps/admin-web
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../apps/admin-web:/app
      - /app/node_modules

  viewer-mobile:
    build:
      context: ../apps/viewer-mobile
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../apps/viewer-mobile:/app
      - /app/node_modules

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: arka_inspection
      POSTGRES_PASSWORD: development_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
